namn =input("vad heter du? ")
print("Ida är ett fint namn")
mat =input("vilken mat gillar du? ")
print("Ida korv är verkligen gott.")
Pengar =input("hur mycket pengar har du i fickan? ")
print("Ida du är rik")